name: newsapp_with_flutter
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  webview_flutter: ^0.3.22+1
  cupertino_icons: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

